# Phoneme vocabulary settings.
phoneme_vocab_size: 134            # Should match the number of tokens returned by get_fixed_inventory()
phoneme_embedding_dim: 256         # Dimension of phoneme embeddings

# Language and speaker embedding settings.
language_vocab_size: 4             # For languages: {en, gu, bh, kn}
language_embedding_dim: 32         # Dimension for language embeddings
speaker_vocab_size: 8              # Number of speakers in the dataset
speaker_embedding_dim: 32          # Dimension for speaker embeddings

# Model internal dimensions.
hidden_size: 512                   # Hidden size for the model (after input projection)
dropout: 0.1                       # Dropout rate to use throughout the network

# ESPnet2 FastSpeech2 backbone parameters.
adim: 384                          # Attention dimension for ESPnet2 encoder
n_heads: 8                       # Number of attention heads (default is 8)
n_layers: 4                        # Number of layers for both encoder and decoder (if used)
eunits: 1536                       # Number of units in the encoder
dunits: 1536                       # Number of units in the decoder (if applicable)
postnet_layers: 5                  # Number of postnet layers for mel-spectrogram refinement
postnet_chans: 512                 # Number of channels in the postnet
postnet_filts: 5                   # Filter size in the postnet

# Output specification.
mel_dim: 80                        # Number of mel-spectrogram channels

# Training-related parameters (added missing section)
train_config:
  batch_size: 16                    # Batch size for training
  num_epochs: 50                   # Number of epochs to train for
  log_interval: 50                 # How often to log training progress
  checkpoint_save_interval: 5     # How often to save checkpoints (in epochs)

# Additional parameters (if needed)
# Path to pretrained encoder weights
# pretrained_encoder_path: "checkpoints/exp/tts_train_fastspeech2_raw_phn_tacotron_g2p_en_no_space/train.loss.ave_5best.pth"

checkpoint_dir: "acoustic_model_fastspeech2/checkpoints"      # Directory to save checkpoints