# HiFi-GAN Configuration file for fine-tuning

model:
  # Generator configuration
  generator:
    in_channels: 80                  # Input channels (Mel-spectrograms)
    out_channels: 1                   # Output channels (waveform)
    kernel_size: 7                    # Kernel size for convolutions
    stride: 4                         # Stride for convolutions
    num_layers: 3                     # Number of layers in the generator
    hidden_channels: 128              # Number of hidden channels
    residual_channels: 128            # Residual channels for the model

  # Discriminator configuration
  discriminator:
    in_channels: 1                    # Input channels (waveform)
    kernel_size: 5                    # Kernel size for convolutions
    stride: 4                         # Stride for convolutions
    num_layers: 3                     # Number of layers in the discriminator
    hidden_channels: 128              # Number of hidden channels
    residual_channels: 128            # Residual channels for the model

  # Training settings
  batch_size: 16                      # Batch size for training
  lr: 1e-4                            # Learning rate for Adam optimizer
  betas: [0.9, 0.999]                 # Adam optimizer betas
  eps: 1e-8                           # Adam optimizer epsilon
  num_epochs: 200                     # Number of epochs to train
  weight_decay: 0.0                   # Weight decay for the optimizer

  # Loss functions
  adversarial_loss_weight: 1.0        # Weight for adversarial loss
  mel_loss_weight: 45.0               # Weight for mel spectrogram loss
  feature_loss_weight: 0.1            # Weight for feature matching loss

  # Miscellaneous parameters
  sample_rate: 22050                 # Audio sample rate (16 kHz)
  num_mels: 80                        # Number of mel bins
  hop_length: 256                     # Hop length for STFT
  win_length: 1024                    # Window length for STFT

  # Paths
  training_data_path: "dataset"  # Path to the training data
  checkpoint_dir: "code/hifi_gan_vocoder/checkpoints"   # Path to save checkpoints
  log_dir: "code/hifi_gan_vocoder/logs"                    # Path to save logs
